const jsonServer = require('json-server')
const server = jsonServer.create()
const router = jsonServer.router('./json/db.json')
const middlewares = jsonServer.defaults()
server.use(middlewares)
server.use(router)
server.listen(process.env.PORT || 5000, _ => console.log('JSON Server is running 5000'))
